
#  1. numerical & print & input & import

### 總之先來點基本的加減乘除
### 應該......，沒有問題吧

In [1]:
a = 2+3
b = 2-3
c = 2*3
d = 2/3

(a, b, c, d)

(5, -1, 6, 0.6666666666666666)

### 不過，這邊要注意的是變數的處理，
### 口訣是：從右邊灌到左邊。

### 還有我們Python是不用事先宣告變數的。

In [0]:
# 來點不一樣的：同餘
a = 2%3
a

2

In [0]:
# Python裡的指數是這樣表示的
b = 2**3
b

8

關於print

In [0]:
a%b

2

In [3]:
print(b, c, d)

-1 6 0.6666666666666666


In [5]:
a = input()
print(a)

123
123


In [7]:
a = int(input("a?   "))
b = int(input("b?   "))

print(a+b)

a?   2
b?   3
5


In [13]:
import math

#函式庫是個圖書館
math.sqrt(2)

1.4142135623730951

In [0]:
import numpy as np

# 例題一:

請以python計算並印出 $ x^2 + 4x + 2 = 0 $ 的解。 

In [14]:
x1 = (-4+math.sqrt(4**2-4*1*2))/2*1
print(x1)

-0.5857864376269049


In [15]:
x2 = (-4-math.sqrt(4**2-4*1*2))/2*1
print(x2)

-3.414213562373095


# 2. List

In [0]:
l = [1, 2, 3]
l2 = list((1, 2, 3))

In [19]:
l[2]

3

## 其實，學資工的人都很喜歡零號......。

In [0]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

In [0]:
l3 = l1+l2
l3

[1, 2, 3, 4, 5, 6]

### 一些高（懶）級（惰）的用法

In [0]:
l3[2:4]

[3, 4]

In [0]:
l3[::-1]

[6, 5, 4, 3, 2, 1]

# 例題二:
請讓使用者input三個數字，並印出此三數分別而成的list，和三數結合而成的list。
最後再印出三數合成的list之中的第二個數。

In [11]:
import numpy as np

a = int(input())
b = int(input())
c = int(input())
d = [a,b,c]
print(d)
print(d[1])


54
87
88
[54, 87, 88]
87


In [0]:
for i in range(2, 10):
    print(i)

2
3
4
5
6
7
8
9


In [0]:
a = np.array([1, 3, 3])
b = np.array([2, 4, 6])

a+b

array([3, 7, 9])


# 3. if

In [0]:
score = int(input("請輸入你上次的考試成績:  "))

#括弧很重要
if (score >= 60) and (score <= 100):
    print("你及格了。")

elif score < 60:
     print("你被當了。")
    
else:
    print("我書讀不多，你別騙我。")

print("成績輸入完畢。")

請輸入你上次的考試成績:  78
你及格了。
成績輸入完畢。


In [0]:
if 1 >2:
  print("yes")
elif 3<3:
  print("NO")
else:
  pass

### 關於縮排，我想說的其實是......。

# 例題三:

Lotus正在修高等微積分。而老師的成績計算有兩種方案，擇優作為期末成績:

1. 小考20%，期中考35%，期末考45%
2. 期中考40%，期末考60%。

請讓使用者依序輸入自身的小考、期中考、期末考成績，
並輸出他的期末分數。

In [14]:
l = int(input())
m = int(input())
f = int(input())

a = l*0.2 + m * 0.35 + f*0.45
b = m*0.4+ f*0.6

if a > b:
    print(a)
else:
    print(b)

88
90
45
69.35


# 4. for:

In [26]:
print(range(10))

range(0, 10)





# 提醒我下次碰到要講進階的“list comprehension”，速度快很多

# 例題四:
請讓使用者輸入一個數字，並輸出該數字的階乘。

In [28]:
k=1
for i in range(1,int(input())+1):
    k = k*i
print(k)

5
120


In [24]:
list(range(1,int(input())))

11


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# 5. 函式定義與巢狀迴圈:


In [0]:
def add(a, b):
    return a+b

def root(a, b, c):
    return a+b+c

In [0]:
z = int(input())
y = int(input())
x = int(input())

d = root(x, y, z)
print(d)

1
2
3
6


In [0]:
c

3

# 例題五:
請完成下列函式，並使其回傳方程式 $ ax^2+bx+c = 0$的解。

附註:
1. 有兩解時回傳解，並整理成一個list。
2. 恰有一解時回傳一解，並整理成一個list。
3. 無解時回傳0，並印出:「無解！」


In [0]:
def root(a, b, c):
    #請把你的程式碼寫在下面
    
    

In [0]:
a = root(1, 3, 2)
b = root(1, 4, 4)
c = root(1, 19, 1)

In [0]:
for i in range(1, 10):
    for j in range(1, 10):
        print(i, " * ", j, " = ", i*j)

1  *  1  =  1
1  *  2  =  2
1  *  3  =  3
1  *  4  =  4
1  *  5  =  5
1  *  6  =  6
1  *  7  =  7
1  *  8  =  8
1  *  9  =  9
2  *  1  =  2
2  *  2  =  4
2  *  3  =  6
2  *  4  =  8
2  *  5  =  10
2  *  6  =  12
2  *  7  =  14
2  *  8  =  16
2  *  9  =  18
3  *  1  =  3
3  *  2  =  6
3  *  3  =  9
3  *  4  =  12
3  *  5  =  15
3  *  6  =  18
3  *  7  =  21
3  *  8  =  24
3  *  9  =  27
4  *  1  =  4
4  *  2  =  8
4  *  3  =  12
4  *  4  =  16
4  *  5  =  20
4  *  6  =  24
4  *  7  =  28
4  *  8  =  32
4  *  9  =  36
5  *  1  =  5
5  *  2  =  10
5  *  3  =  15
5  *  4  =  20
5  *  5  =  25
5  *  6  =  30
5  *  7  =  35
5  *  8  =  40
5  *  9  =  45
6  *  1  =  6
6  *  2  =  12
6  *  3  =  18
6  *  4  =  24
6  *  5  =  30
6  *  6  =  36
6  *  7  =  42
6  *  8  =  48
6  *  9  =  54
7  *  1  =  7
7  *  2  =  14
7  *  3  =  21
7  *  4  =  28
7  *  5  =  35
7  *  6  =  42
7  *  7  =  49
7  *  8  =  56
7  *  9  =  63
8  *  1  =  8
8  *  2  =  16
8  *  3  =  24
8  *  4  =  32
8  *  5  =  40
8 

# 例題六
請定義一個函式，使其在接收輸入n之後，印出一個n層的金字塔。

In [38]:
for i in range(1,int(input())+1):
    a=[i]
    print(a*i)

10
[1]
[2, 2]
[3, 3, 3]
[4, 4, 4, 4]
[5, 5, 5, 5, 5]
[6, 6, 6, 6, 6, 6]
[7, 7, 7, 7, 7, 7, 7]
[8, 8, 8, 8, 8, 8, 8, 8]
[9, 9, 9, 9, 9, 9, 9, 9, 9]
[10, 10, 10, 10, 10, 10, 10, 10, 10, 10]


# 6. numpy 

In [0]:
import numpy as np

In [0]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [0]:
a+b

array([5, 7, 9])

In [0]:
a*b

array([ 4, 10, 18])

In [0]:
np.random.randint(0, 256, size=(256, 256))

array([[136,  53, 169, ...,  18, 126,  64],
       [160, 164, 131, ...,  11, 120, 131],
       [134, 126,  97, ..., 132,  20,  58],
       ..., 
       [  7, 138,  93, ..., 144,  75, 153],
       [208, 251, 113, ...,  26,  86, 234],
       [ 95, 241, 251, ...,  47,  76, 222]])